### ISSUE TITLE
Definamos los ESTILOS GLOBALES

### ISSUE THREAD

**Issue by CodigoLatino** [CodigoLatino/MEMORAR_APP#1]
Debemos definir con que _estilo_ diseñaremos el proyecto completo, para poder tener una base del mismo.

**Todo debe documentarse** para tener los colores primordiales y estilos de diseño en todas las áreas del proyecto 🚀 .

- [x] COLORES 🖌️ 
- [x] ESTILOS 🥇 
- [x] ANIMACIONES 💹 
- [x] TypeRENDERS 🧾 

Comenten sus propuestas de estilos...

**Comment by JAAvila-Of** [comment]
Que tal un estilo IOS?

**Comment by jcdelrioe** [comment]
He leído algo de neumorphismo [https://koncep.to/after-effects/blog/neumorfismo-en-las-interfaces-de-usuario-tendencia-de-ux-ui-para-el-2020/](url) , me parece interesante como diseño aunque para temas de accesibilidad no es tan bueno

**Comment by JAAvila-Of** [comment]
me parece muy atractivo visualmente, habría que ver como se puede resolver el asunto de rendimiento y accesibilidad, esperemos a que dicen los demás

**Comment by rafcallata** [comment]
hola @JAAvila-Of el estilo IOS es para todas las plataformas o solo para el celular, te refieres a eso??
me parece bien lo que dice @jcdelrioe 
soy nuevo trabajando en algo real pero hasta donde leí es bueno solo tener 3 colores para el fondo nav y el contenido 
y colores primarios para los botones o enlaces 
para el código yo sugeriría hacerlo en español, pero se que no es una buena practica. si va ser en ingles el código seria bueno siempre decir que hace esa linea de código
bueno esa seria mi opinión de novato.

**Comment by Dreamlocked** [comment]
Creo que al ser uno de los primeros proyectos, para colores y estilos, creo que optar por materia ui es lo mejor, ya que hay mucha información sobre las gama de colores, hasta generadores a partir de un color base y layouts

**Comment by JAAvila-Of** [comment]
> Creo que al ser uno de los primeros proyectos, para colores y estilos, creo que optar por materia ui es lo mejor, ya que hay mucha información sobre las gama de colores, hasta generadores a partir de un color base y layouts

igual y me gusta lo que comentas, esperemos a que los demás opinen y ver como quedamos, el HITO vence en dos días para coordinar todo esto y empezar a asignar las tareas

**Comment by guadalupe182** [comment]
concuerdo con @Dreamlocked por la cantidad de informacion que hay al respecto

**Comment by Lestradez** [comment]
> Creo que al ser uno de los primeros proyectos, para colores y estilos, creo que optar por materia ui es lo mejor, ya que hay mucha información sobre las gama de colores, hasta generadores a partir de un color base y layouts
>
`Coincido`

**Comment by Hatori1014** [comment]
@Dreamlocked concuerdo con el.

**Comment by GeerDev** [comment]
Concuerdo también con @Dreamlocked , creo que estaría bien utilizar los componentes UI predefinidos en Tailwind Css y personalizarlos a nuestro gusto, además podemos añadir algún componente con glassmorphism, el efecto este difuminado que queda muy chulo. Para el panel de administración utilizaria la biblioteca Material UI de React.

Con respecto a los colores utilizaria una paleta de colores ya predefinida elegida en [(https://coolors.co/)].

Yo no tengo muy claro la funcionalidad de la aplicación, más allá de que va a ser una aplicación para gestionar las tareas del día a día, estaría bien que para tener claro los objetivos a cumplir diseñaramos una tabla de funcionalidades con prioridades y unos mock ups para saber que interfaces vamos a tener, cuantas van a ser y como va a se un poquito la experiencia de usuario navegando entre ellas. A mi personalmente no me agrada mucho diseñar mock ups pero creo que deberíamos tener unos prototipos para saber más o menos que queremos diseñar.

**Comment by JAAvila-Of** [comment]
![Captura de pantalla 2021-04-20 101815](https://user-images.githubusercontent.com/69764058/115421696-c7eead00-a1c1-11eb-8552-31e1023249e4.jpg)
Les parece este estilo de colores , es un estilo retro pero muy atractivo
Visualmente creo que caería muy bien! o alguna propuesta?

**Comment by CodigoLatino** [comment]
Doy por finalizado las propuestas para los estilos, pues por conveniencia al ser el primer proyecto nos enfocaremos en utilizar solo TailwindCSS y maquetado con un poco de MATERIAL DESIGN, eso quiere decir que 3 de los objetivos de este primer ISSUE están completados, ESTILOS, ANIMACIONES y TYPERENDERS. Solo faltaría el de COLORES!!

**Comment by guadalupe182** [comment]
Que tal esta?

 
![paleta de colores](https://user-images.githubusercontent.com/76502431/115423505-80692080-a1c3-11eb-98bf-a7d83f688538.jpg)

**Comment by guadalupe182** [comment]
otra propuesta...

![pcolores](https://user-images.githubusercontent.com/76502431/115424271-29178000-a1c4-11eb-9a64-442df4c334f7.png)

**Comment by guadalupe182** [comment]
Mi ultima propuesta

![Coolors-paleta-colores](https://user-images.githubusercontent.com/76502431/115424462-582df180-a1c4-11eb-9393-38f4dedf4539.png)

**Comment by GeerDev** [comment]
Me gustan la paleta de colores que ha propuesto @JAAvila-Of y la de minimal colors de @guadalupe182

**Comment by JAAvila-Of** [comment]
creo que esta muy bien la de minimal colors tambien, esperemos a que los demás opinen.

**Comment by CodigoLatino** [comment]
MUYB BIEN LLEGAMOS AL FIN, Y CON ESTO LOS COLORES SERÁN MINIMAL COLORS, EN BASE A ESO TRABAJAREMOS LA APLICACIÓN!!, DOY POR CERRADO ESTE ISSUE Y SUS DERIVADOS.
