### ISSUE TITLE
PLANIFIQUEMOS LAS HERRAMIENTAS A UTILIZAR!!

### ISSUE THREAD

**Issue by CodigoLatino** [CodigoLatino/MEMORAR_APP#2]
Tenemos que planificar todas las **Herramientas a usar**, esto es importante para que el orden general del código no se pierda.
Definiremos las herramientas en **3 categorías**:

- [x] Herramientas de Documentación: _Notion, GitHub WIKI, Personal WEB_.
- [x] Herramientas de Integración Colaborativo: _Slack, Discord, Meet_.
- [x] Herramientas de Desarrollo: _VSCODE - Prettier, esLint, custom config_.

**Comment by guadalupe182** [comment]
Github wiki/Meet/VScode

**Comment by GeerDev** [comment]
Github Wiki/Slack/VSCODE - extensiones Prettier, Auto close tag, Material Icon Theme, Snippets React...

**Comment by dvicenter** [comment]
se podría usar Jira ?

**Comment by Hatori1014** [comment]
Github Notion / Discord / VSCODE - Extensiones Prettier, gitlens, Bracket Pair Colorizer, snippets para react, tailwind, etc..

**Comment by JAAvila-Of** [comment]
creo que mejor hay que ir por partes, para las herramientas de Documentación yo propongo GitHub wiki, que dicen?

**Comment by guadalupe182** [comment]
para colaborativo podria ser meet para solucion de problemas hacer un tipo pair programming

**Comment by Lestradez** [comment]
Para Herramientas de Integración Colaborativo me parece bien cualquiera: Meet, Jitsi, Zoom, Discord o Teams, pero habría que ver el tema de la conexión porque durante la nivelación se me hizo complicado seguir a Jose, se escuchaba mal y el video iba bastante a destiempo del audio. (Desconozco qué es el pair programming)

**Comment by Dreamlocked** [comment]
Creo que para la herramienta de integración, creo que en mi caso escogería discord, ya que su AI filtra ruido y mejora el audio en reuniones, aunque creo que los directos están solo a 720p. En cuanto a meet, no tiene eso y en slack no lo he usado :/ .

**Comment by CodigoLatino** [comment]
Las herramientas a usar son las siguientes GitHub WIKI para documentacion, Meet para la parte colaborativa y Prettier.
Doy por cerrado este ISSUE
