### ISSUE TITLE
PLANIFIQUEMOS LOS EQUIPOS DE TRABAJO

### ISSUE THREAD

**Issue by CodigoLatino** [CodigoLatino/MEMORAR_APP#3]
En esta parte tenemos que planificar los equipo de trabajo:

- [x] Equipo de Diseño
- [x] Equipo de Lógica
- [x] Equipo de Testing
- [x] Equipo de UX

De estos equipos los más primordiales a definir son los dos primeros, asi que los que se sientan más cómodos con Diseño Web, únanse al equipo de diseño y los que se sientan más cómodos con Backend únanse al equipo de lógica.
Tenemos solo 1 día para decidir.

**Comment by Lestradez** [comment]
Buenos días! Diseño y lógica en ese orden.

**Comment by jcdelrioe** [comment]
Buenos días no tengo mayor conocimiento en Diseño, yo optaría por lógica

**Comment by GeerDev** [comment]
Diseño, pero no me importa tocar cualquiera de los otros temas

**Comment by guadalupe182** [comment]
# lógica ^^

**Comment by dvicenter** [comment]
yo manejo mas backend, pero estoy practicando el front , asi que me gustaría estar en el front en este proyecto, y podría apoyar en el back tambien.

**Comment by Dreamlocked** [comment]
Me gustaría aprender backend, por lo que estaría en lógica; pero, de igual manera, si falta apoyo en frontend, apoyaré.

**Comment by Hatori1014** [comment]
**Lógica**, aunque me gustaría apoyar en cualquier otro equipo

**Comment by CodigoLatino** [comment]
Falta poco para terminar esta ISSUE, esperemos un poco más para determinar los equipos!!

**Comment by CodigoLatino** [comment]
Doy por finalizado la ISSUE junto a la MILESTONE con lo siguiente:

En ESTILOS GENERALES tenemos:
- COLORES: MINIMAL COLORS propuesto por @guadalupe182 
- ESTILOS: TailwindCSS
- ANIMACIONES: TailwindCSS
- typeRENDERS: TailwindCSS

En HERRAMIENTAS GENERALES tenemos:
- DOCUMENTACION: GitHub WIKI
- COLABORATIVO: MEET
- DESARROLLO: VSCODE - Prettier

En EQUIPOS tenemos:
- Diseño:
    - @Lestradez 
    - @Gerahara 
    - @dvicenter 
- LÓGICA:
    - @jcdelrioe 
    - @guadalupe182 
    - @Dreamlocked 
    - @Hatori1014 
Todos los demás se incorporarán según requerimiento.

En METODOLOGÍAS tenemos:
- Kanban
- UML

En TECNOLOGÍAS tenemos:
- ReactJS
- TailwindCSS
- Typescript

Y CON ESTO DAMOS POR FINALIZADO TODOS LOS PREPARATIVOS, EN EL TRANSCURSO DEL DIA, SE PUBLICARÁ EL PRIMER COMMIT DEL PROYECTO Y SE DELEGARÁN LAS TAREAS, GRACIAS!!!!!
